run:
  deadline: 2m
  tests: true

  skip-dirs-use-default: true

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  nakedret:
    max-func-lines: 50

linters:
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - goconst
    - gocritic
    - nakedret
    - nestif
    - prealloc
    - stylecheck
    - typecheck
    - unconvert
    - unparam
  fast: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "always receives"
    - "parameter .* is always"
    - "comment on exported .* should be of the form"

output:
  format: colored-line-number